// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Channel string
	Message string
	User    string
}{
	Channel: "channel",
	Message: "message",
	User:    "user",
}
