// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Channel        string
	File           string
	Message        string
	RelMessageFile string
	User           string
	UserProfile    string
}{
	Channel:        "channel",
	File:           "file",
	Message:        "message",
	RelMessageFile: "rel_message_file",
	User:           "user",
	UserProfile:    "user_profile",
}
